name: do-app-platform-nextjs
region: nyc
services:
    - build_command: npm run build
      environment_slug: node-js
      github:
          branch: main
          deploy_on_push: true
          repo: sorensenjg/do-app-platform-nextjs
      http_port: 8080
      instance_count: 1
      instance_size_slug: basic-xxs
      name: do-app-platform-nextjs
      routes:
          - path: /
      run_command: npm run start
